version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: appJuegosdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d	
  
  app:	
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/appJuegosdb
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: clave
volumes:
  mysqldata: